dailyResetTime: "05:00"
contractsPerDay: 3
generateOnJoin: true
maxActiveContracts: 3

antiAbuse:
  placedBlockTtlMinutes: 360
  cleanupIntervalSeconds: 120

gui:
  titleMain: "<gold>Доска контрактов</gold>"
  titleFaction: "<gold>Контракты - %faction%</gold>"

ranks:
  "0": Новичок
  "500": Ученик
  "1500": Эксперт
  "4000": Мастер
